#################
### AUTOSTART ###
#################


exec-once = $terminal
exec-once = hyprctl setcursor Bibata-Modern-Classic 20
exec-once = /usr/local/bin/au run
exec-once = wl-paste --watch cliphist store
