plugin {
  hyprbars {
    # example config
    bar_height = 20
    bar_precedence_over_border = true
    bar_buttons_alignment = left
    bar_padding = 10
    bar_color = rgba(555555ff)
    bar_part_of_window = false
    bar_text_size = 10
    hyprbars-button = rgb(ff5f56), 15,, hyprctl dispatch killactive
    hyprbars-button = rgb(ffbd2e), 15,, hyprctl dispatch minimize
    hyprbars-button = rgb(27c93f), 15,, hyprctl dispatch fullscreen 1
  }
  dynamic-cursors {
      enabled = true
      mode = shake
  	  threshold = 2
      shake {
          enabled = true
          nearest = true
          threshold = 6.0
          base = 3.0
          speed = 2.0
          influence = 0.0
          limit = 4.0
          timeout = 1500
  		  effects = false
      }
      hyprcursor {
          nearest = 2
          enabled = true
          resolution = -1
          fallback = clientside
      }
   }
   liquid-glass {
       enabled = true
       blur_strength = 1.0
       refraction_strength = 0.04
       chromatic_aberration = 0.004
       fresnel_strength = 1.0
       specular_strength = 0.0
       glass_opacity = 1.0
       red_tint = 0.2
       blue_tint = 0.2
       green_tint = 0.2
       edge_thickness = 0.15
   }
}


